version: "3"
services:
  db:
    container_name: db
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=communication_system
      - MYSQL_USER=devops
      - MYSQL_PASSWORD=96544
    env_file:
      - web/.env
    volumes:
      - ./mysqldata:/var/lib/mysql:rw,delegated
      #- db_data:/var/lib/mysql
  web:
    depends_on:
      - db
    build:
      context: ./web
      dockerfile: Dockerfile
    image: django-k8s:v1
    environment:
      - PORT=8020
    env_file:
      - web/.env
    ports:
      - "8001:8020"
    command:
      - /bin/bash
      - -c
      - |
        sleep 10
        chmod +x /app/migrate.sh
        sh /app/migrate.sh
        sh  /app/entrypoint.sh

volumes:
  db_data:
