version: "3"
services:
  db:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=communication_system
      - MYSQL_USER=devops
      - MYSQL_PASSWORD=96544
      - MYSQL_ROOT_PASSWORD=96544
    volumes:
      - db_data:/var/lib/mysql
  web:
    build: .
    command:
      - /bin/bash
      - -c
      - |
        sleep 10
        python3 manage.py migrate
        python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    links:
      - db
volumes:
  db_data:
