apiVersion: v1
kind: Service
metadata:
  name: django-mysql
  labels:
    app: django
spec:
  ports:
    - port: 3306
  selector:
    app: django
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-mysql-pvc
  labels:
    app: django
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: django-mysql
spec:
  selector:
    matchLabels:
      app: django
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: django
        tier: mysql
    spec:
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: django-mysql-pvc
      containers:
        - image: mysql:latest
          name: mysql
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
          env:
            - name: MYSQL_DATABASE
              value: communication_system
            - name: MYSQL_USER
              value: devops
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-password
                  key: password
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-password
                  key: password
