apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-mysql-pvc
  labels:
    app: django
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: django-mysql
spec:
  selector:
    matchLabels:
      app: django
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: django
        tier: mysql
    spec:
      volumes:
        - name: mysql-data
          PersistentVolumeClaim:
            claimName: django-mysql-pvc
      containers:
        - image: mysql:latest
          name: mysql
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql/data
          env:
            - name: MYSQL_DATABASE
              value: communication_system
            - name: MYSQL_USER
              value: devops
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-password
                  key: password
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-password
                  key: password
